rules:
- id: use-log-targets
  languages:
    - rust
  message: Log statements should have static target defined to aid filtering
  patterns:
    # semgrep struggles with finding boundaries of rust macro invocation when ellipsis (`...`) is used
    # so matching this one with raw regexes instead
    - pattern-regex: (error|warn|info)!\([^;]*?\);
    - pattern-not-regex: '(error|warn|info)!\(\s*target: [^;]*?\);'

  severity: WARNING
